#! /bin/bash

ZIP="/bin/zip"

key=$1
# filename=$2
# new_folder=$3
# res='result_packed'


# encrypted_filename=$2
files=$@
prefix='PRE'
build_dir='build'

pk_dir() { $ZIP -r $1.zip $1; }
pk_files() { $ZIP -r $1 ./*; }

dated_name() { echo "$1_$(date '+%Y%m%d_%H%M')"; }
encrypt() { gpg -r $1 --encrypt $2; }

rm -rf $build_dir
mkdir $build_dir

# mv $encrypted_filename $build_dir
mv $files $build_dir

cd $build_dir

zip_filename=${prefix}$(dated_name result).zip
pk_files $zip_filename
encrypt $1 $zip_filename

mv ${zip_filename}.gpg ../
cd ../
rm -rf build

# encrypt mykey@abc.net folder.zip

# pack <gpg_public_key_fingerpring> <existing.zip.gpg> new_folder/

# rename_folder() { mv $1 $(dated_name $1); echo $(dated_name $1); }
# dated_new_folder=$(rename_folder $new_folder)

# mkdir $res
# mv $dated_new_folder $res
# mv $filename $res

# pk $res
# encrypt $1 ${res}.zip

# rm -rf ${res}
# rm ${res}.zip
