#! /bin/bash

key=$1
# filename=$2
# new_folder=$3
# res='result_packed'


# encrypted_filename=$2
files=$@
prefix='PRE'
build_dir='build'

pk_dir() { zip -r $1.zip $1; }
pk_files() { zip -r $1 ./*; }
archived_filename() { echo $1.zip; }

dated_name() { echo "$1_$(date '+%Y%m%d_%H%M')"; }
encrypt() { gpg -r $1 --encrypt $2; }

rm -rf $build_dir
mkdir $build_dir

# mv $encrypted_filename $build_dir
mv $files $build_dir

cd $build_dir

packed_filename=$(archived_filename ${prefix}$(dated_name result) )
pk_files $packed_filename
encrypt $1 $packed_filename

mv ${packed_filename}.gpg ../
cd ../
rm -rf build
